version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    command: bash -c "cargo watch -x run"
    ports:
      - "3000:3000"
    environment:
      RUST_LOG: info
      DATABASE_URL: postgresql://postgres:mypassword@db:5432/docker
    depends_on:
      - db
    volumes:
      - rust-target:/app/target
      - ./:/app/
volumes:
  rust-target:
  postgres-data:

